# https://github.com/srcery-colors/srcery-terminal/

[colors.primary]
background = "#1c1b19"
foreground = "#fce8c3"

[colors.cursor]
text = "CellBackground"
cursor = "#fbb829"

[colors.normal]
black = "#1c1b19"
red = "#ef2f27"
green = "#519f50"
yellow = "#fbb829"
blue = "#2c78bf"
magenta = "#e02c6d"
cyan = "#0aaeb3"
white = "#baa67f"

[colors.bright]
black = "#918175"
red = "#f75341"
green = "#98bc37"
yellow = "#fed06e"
blue = "#68a8e4"
magenta = "#ff5c8f"
cyan = "#2be4d0"
white = "#fce8c3"
